# This script is used for preprocess behavior data and replicates behavior results in Bayesian framework

```{r}
library(brms) 
library(tidyverse) 
library(bruceR)
library(bayestestR)
library(papaja)
library(smplot2)
library(patchwork)

```

```{md}
# Data preparation: 
# 1. Set configuration and constants
# 2. Merge all behavior data into all one


# Analysis 1: compare accuracy with chance level between 1and 4 distributions in each single feature

# 1. Select 1 and 4 in column of 'cue_dimensionality'
# 2. Use brms to calculate the difference of accuracy
# 3. Models diagnosis
# 4. Statistic inference
# 5. plot 

# Analysis 2: Compare ACC and RT between different distributions
# 1. Set and sample Bayesian models for ACC and RT
# 2. Models diagnosis
# 3. Statistic inference
# 4. plot 
```

##########
## Data preparation
#########

```{r (1_1)}
# Configuration and Constants
PATH_RAW_DATA = '../data/behaviorData'

SUBJECT_IDX <- paste0("sub-STSWD", c(
  1117,1118,1120,1126,1131,1132,1135,1136,
  1151,1160,1164,1167,1169,1172,1173,1178,
  1182,1215,1216,1219,1223,1227,1228,1233,
  1234,1237,1240,1243,1245,1247,1250,1239,
  1252,1257,1261,1265,1266,1268,1270,1276,1281
))

BIDS_TASK_LABEL_BEH = '_task-MAT_behavEEG'

probe_idx <- c('1','2','3','4')
cue_levels <- c('1', '4')

```

```{r for merge data. (1_2)}
# Load behavior data and merge into a full dataframe.
behavior_list <- list()

for (sub_idx in SUBJECT_IDX) {
  # cat("Processing subject:", sub_idx, "\n")  
  # Set path
  path_beh <- file.path(
    PATH_RAW_DATA,
    paste0(sub_idx, BIDS_TASK_LABEL_BEH, ".csv")
  )

  # Check the path
  if (!file.exists(path_beh)) stop("Behavior file not found: ", path_beh)

  # Load behavior data 
  data_behavior <- read.csv(path_beh, sep = ",", header = TRUE, check.names = FALSE)
  # Add 'subj_idx'
  data_behavior['subj_idx'] <- sub_idx
  data_behavior$subj_idx <- str_remove(sub_idx, "sub-STSWD")
  # Make a list
  behavior_list[[sub_idx]] <- data_behavior
}

data_behavior_full <- bind_rows(behavior_list)
data_behavior_full$probe_attribute <- as.factor(data_behavior_full$probe_attribute)
data_behavior_full$cue_dimensionality <- as.factor(data_behavior_full$cue_dimensionality)

# Drop missing values
data_behavior_full <- data_behavior_full %>% 
  dplyr::filter(!is.na(probe_accuracy))

# Data for analysis
data_analysis <- data_behavior_full %>%
  group_by(subj_idx, probe_attribute, cue_dimensionality) %>%
  summarise(
    mean_acc = mean(probe_accuracy, na.rm = TRUE),
    media_rt = median(probe_rt, na.rm = TRUE),
    .groups = "drop"
  ) 

# Data plot for analysis 1
data_plot_analysis_1 <- data_behavior_full %>%
  dplyr::filter(
    #probe_attribute == probe_idx,
    cue_dimensionality %in% cue_levels
    )%>%
  group_by(subj_idx, probe_attribute, cue_dimensionality) %>%
  summarise(
    mean_acc = mean(probe_accuracy, na.rm = TRUE),
    .groups = "drop"
  ) 

```

##########
## Analysis 1
#########

```{r for model setting. (2_1,2)}
# Compare ACC against chance level for different single feature under both '1' and '4' loading effect 
model_list_analysis_1 <- list()

for (probe in probe_idx) {
  for (cue in cue_levels) {
    df_sub <- data_analysis %>%
      dplyr::filter(
        probe_attribute == probe,
        cue_dimensionality == cue
      )
    
    # Set Bayesian model and smapling
    model <- brms::brm(
      mean_acc ~ 1 + (1|subj_idx),
      data = df_sub,
      family = gaussian(),
      iter = 2000,
      warmup = 1000,
      chains = 4,
      cores = 4,
      seed = 42,
    )
    
    # name：model_prove1_cue1, model_prove1_cue4, etc.
    model_name <- paste0("model_accuracy_probe", probe, "_cue", cue)
    model_list_analysis_1[[model_name]] <- model
  }
}

saveRDS(model_list_analysis_1, "../results/model_list_analysis_1_partial_pooling.rds")

```

```{r for model diagnosis.(2_3)}
# Define a function to diagnose all models
model_diagnostics <- function(model_list) {
  # Set dataframe to save data
  results <- data.frame(
    model_name = names(model_list),
    Rhat = NA,
    bulk_ESS = NA
  )
  
  # Summary and extract value
  for (i in seq_along(model_list)) {
    m <- model_list[[i]]
    m_summary = summary(m)
    results$Rhat[i] <- m_summary$fixed$Rhat
    results$bulk_ESS[i] <- m_summary$fixed$Bulk_ESS
    
  }
  
  return(results)
}

# diagnose 8 models
# If you clear your workplace, you can use the code below to load models, which were made by last chunks
# model_list_analysis_1 <- readRDS("../results/model_list_analysis_1_partial_pooling.rds")
diagnosis_table_analysis_1 <- model_diagnostics(model_list_analysis_1)
print(diagnosis_table_analysis_1)

```

```{r for specific model}

df_sub <- data_analysis %>%
  dplyr::filter(
    probe_attribute == 3,
    cue_dimensionality == 1
  )
    
model <- brms::brm(
  mean_acc ~ 1 + (1|subj_idx),
  data = df_sub,
  family = gaussian(),
  iter = 4000,
  warmup = 1000,
  chains = 4,
  cores = 4,
  seed = 42,
    )

summary(model)
```


```{r for statistic inference. (2_4)}
plot_list <- list()

for (m in seq_along(model_list_analysis_1)){
  model <- model_list_analysis_1[[m]]
  model_name <- names(model_list_analysis_1)[[m]]
  trace_par <- as.data.frame(model)$b_Intercept
  hdi <- bayestestR::hdi(trace_par, ci = 0.95)
  rope_res <- bayestestR::rope(trace_par, range = c(0.45, 0.55))
  
  p <- plot(rope_res, rope_color = "grey70") +
    papaja::theme_apa() +
    ggtitle(paste(model_name))
  
  plot_list[[m]] <- p
}

final_plot_analysis_1 <- patchwork::wrap_plots(plot_list, ncol = 4)+
  ggview::canvas(width = 400,height = 200*2/3, units = "mm", dpi = 320)
print(final_plot_analysis_1)

ggplot2::ggsave(
  filename = '../figure/final_plot_analysis_1.jpg',
  plot = final_plot_analysis_1,                
  width = 400,                       
  height = 200*2/3,                       
  units = "mm",
  dpi = 320
)

```

```{r for plot}
p_analysis_1_describe = ggplot(data = data_plot_analysis_1, 
       aes(x = probe_attribute, y = mean_acc, group = cue_dimensionality, color = cue_dimensionality)) +
  smplot2::sm_bar(
    position = position_dodge(width = 0.7)) +
  scale_color_manual(values = sm_color('wine','skyblue','lightbrown','yelloworange'))

ggplot2::ggsave(
  filename = '../figure/p_analysis_1_describe.jpg',
  plot = p_analysis_1_describe,                
  width = 400,                       
  height = 200*2/3,                       
  units = "mm",
  dpi = 320
)
```

#########
## Analysis 2
########
```{r for models setting .(3_1)}

# Set Bayesian model and sampling
# Model4ACC
models_list_analysis_2 <- list()

model_acc <- brms::brm(
  mean_acc ~ 1 + cue_dimensionality + (1 + cue_dimensionality|subj_idx),
  data = data_analysis,
  family = gaussian(),
  iter = 2000,
  warmup = 1000,
  chains = 4,
  cores = 4,
  seed = 42)
model_name_acc <- paste0("model_acc_analysis_2")
models_list_analysis_2[[model_name_acc]] <- model_acc

# Model4RT
model_rt <- brms::brm(
  media_rt ~ 1 + cue_dimensionality + (1 + cue_dimensionality|subj_idx),
  data = data_analysis,
  family = gaussian(),
  iter = 2000,
  warmup = 1000,
  chains = 4,
  cores = 4,
  seed = 42)
model_name_rt <- paste0("model_rt_analysis_2")
model_list_analysis_2[[model_name_rt]] <- model_rt

saveRDS(model_list_analysis_2, "../results/model_list_analysis_2_partial_pooling.rds")
```

```{r for model diagnosis.(3_2)}

diagnosis_table_analysis_2 <- model_diagnostics(model_list_analysis_2)
print(diagnosis_table_analysis_2)

```


```{r for statistic inference. (3_3)}
model_list_analysis_2 <- readRDS("../results/model_list_analysis_2_partial_pooling.rds")
a = as.data.frame(model_list_analysis_2[[1]])
summary(model_list_analysis_2[[1]])

plot_list <- list()

for (m in seq_along(model_list_analysis_2)){
  model <- model_list_analysis_2[[m]]
  model_name <- names(model_list_analysis_2)[[m]]
  
  trace_par_cue2vs1 <- as.data.frame(model)$b_cue_dimensionality2
  trace_par_cue3vs1 <- as.data.frame(model)$b_cue_dimensionality3
  trace_par_cue4vs1 <- as.data.frame(model)$b_cue_dimensionality4
  
  trace_par_cue3vs2 = trace_par_cue3vs1-trace_par_cue2vs1
  trace_par_cue4vs2 = trace_par_cue4vs1-trace_par_cue2vs1
  trace_par_cue4vs3 = trace_par_cue4vs1-trace_par_cue3vs1
  
  hdi_3vs2 <- bayestestR::hdi(trace_par_cue3vs2, ci = 0.95)
  rope_res_2 <- bayestestR::rope(trace_par_cue3vs2, range = c(-0.1,0.1))
                                 
  hdi_4vs2 <- bayestestR::hdi(trace_par_cue4vs2, ci = 0.95)
  rope_res_3 <- bayestestR::rope(trace_par_cue4vs2, range = c(-0.1,0.1))
  
  hdi_4vs3 <- bayestestR::hdi(trace_par_cue4vs3, ci = 0.95)
  rope_res_4 <- bayestestR::rope(trace_par_cue4vs3, range = c(-0.1,0.1))
  
  p_3vs2 <- plot(rope_res_2, rope_color = "grey70") +
    papaja::theme_apa() +
    ggtitle(paste(model_name, 'cue3vs2'))
  
  p_4vs2 <- plot(rope_res_3, rope_color = "grey70") +
    papaja::theme_apa() +
    ggtitle(paste(model_name, 'cue4vs2'))
  
  p_4vs3 <- plot(rope_res_4, rope_color = "grey70") +
    papaja::theme_apa() +
    ggtitle(paste(model_name, 'cue4vs3'))
  
  plot_list <- c(plot_list, p_3vs2, p_4vs2, p_4vs3)
}

final_plot_analysis_2 <- patchwork::wrap_plots(plot_list, ncol = 3)
final_plot_analysis_2+ggview::canvas(width = 400,height = 200*2/3, units = "mm", dpi = 320)

ggplot2::ggsave(
  filename = '../figure/final_plot_analysis_2.jpg',
  plot = final_plot_analysis_2,                
  width = 400,                       
  height = 200*2/3,                       
  units = "mm",
  dpi = 320
)
```

```{r for plot (3_4)}
p_acc = ggplot(data = data_analysis, mapping = aes(x = cue_dimensionality, y = mean_acc, fill = cue_dimensionality)) +
  sm_raincloud() +
  scale_fill_manual(values = sm_color("darkred", "viridian",'yelloworange','wine'))

p_rt = ggplot(data = data_analysis, mapping = aes(x = cue_dimensionality, y = media_rt, fill = cue_dimensionality)) +
  sm_raincloud() +
  scale_fill_manual(values = sm_color("darkred", "viridian",'yelloworange','wine'))

p_acc+p_rt+ggview::canvas(width = 300,height = 200*2/3, units = "mm", dpi = 320)

p_analysis_2_describe = p_acc+p_rt

ggplot2::ggsave(
  filename = '../figure/p_analysis_2_describe.jpg',
  plot = p_analysis_2_describe,                
  width = 300,                       
  height = 200*2/3,                       
  units = "mm",
  dpi = 320
)

```


```{r}


```
