# This script plots dic plot for 4 models and make statistic inference for drift rate

```{r}
library(brms) 
library(tidyverse) 
library(bruceR)
library(bayestestR)
library(papaja)
library(smplot2)
library(patchwork)

```

```{r for Configuration and constant}
PATH_DIC <- '../results/hddm/dic_model_full.csv'
PATH_A <- '../results/hddm/data_posterior_a.csv'
PATH_V <- '../results/hddm/data_posterior_v.csv'
PATH_T <- '../results/hddm/data_posterior_t.csv'

```

```{r for plot dic}
data_dic <- read.csv(PATH_DIC)
data_dic_difference <- data_dic[2:5,]
data_dic_difference[, 2] <- data_dic_difference[, 2] - data_dic[1, 2]

figure_dic = ggplot(data = data_dic_difference, mapping = aes(x = model, y = DIC/1000)) +
  smplot2::sm_bar(
     bar.params = list(width = 0.5)
  )+
   scale_y_continuous(
    name = "DIC (×10³)"
  )
figure_dic+ggview::canvas(width = 200,height = 400*2/3, units = "mm", dpi = 320)
ggsave(
  filename = '../figure/plot_dic.jpg',
  plot = figure_dic,                
  width = 200,                       
  height = 400*2/3,                       
  units = "mm",
  dpi = 320
)

```

```{r for statistic inference_load data and plot posterior values}

# load data and change into long data
data_posterior_a <- read.csv(PATH_A)
data_posterior_a_long <- data_posterior_a %>%
  tidyr::pivot_longer(
    cols = everything(),  
    names_to = "a_condition", 
    values_to = "a_value"
  )

data_posterior_v <- read.csv(PATH_V)
data_posterior_v_long <- data_posterior_v %>%
  tidyr::pivot_longer(
    cols = everything(),
    names_to = "v_condition",         
    values_to = "v_value" 
  )

data_posterior_t <- read.csv(PATH_T)
data_posterior_t_long <- data_posterior_t %>%
  tidyr::pivot_longer(
    cols = everything(),
    names_to = "t_condition",         
    values_to = "t_value" 
  )


### plot
# a
figure_hddm_a = ggplot(data = data_posterior_a_long, mapping = aes(x = a_condition, y = a_value, fill = a_condition)) +
  sm_raincloud(which_side = "l") +
  scale_fill_manual(values = sm_color("darkred", "viridian",'yelloworange','wine'))
figure_hddm_a+ggview::canvas(width = 300,height = 400*2/3, units = "mm", dpi = 320)

ggsave(
  filename = '../figure/plot_hddm_a.jpg',
  plot = figure_hddm_a,                
  width = 300,                       
  height = 400*2/3,                       
  units = "mm",
  dpi = 320
)

# v
figure_hddm_v = ggplot(data = data_posterior_v_long, mapping = aes(x = v_condition, y = v_value, fill = v_condition)) +
  sm_raincloud(which_side = "l") +
  scale_fill_manual(values = sm_color("darkred", "viridian",'yelloworange','wine'))
figure_hddm_v+ggview::canvas(width = 300,height = 400*2/3, units = "mm", dpi = 320)

ggsave(
  filename = '../figure/plot_hddm_v.jpg',
  plot = figure_hddm_v,                
  width = 300,                       
  height = 400*2/3,                       
  units = "mm",
  dpi = 320
)

# t
figure_hddm_t = ggplot(data = data_posterior_t_long, mapping = aes(x = t_condition, y = t_value, fill = t_condition)) +
  sm_raincloud(which_side = "l") +
  scale_fill_manual(values = sm_color("darkred", "viridian",'yelloworange','wine'))
figure_hddm_t+ggview::canvas(width = 300,height = 400*2/3, units = "mm", dpi = 320)

ggsave(
  filename = '../figure/plot_hddm_t.jpg',
  plot = figure_hddm_t,                
  width = 300,                       
  height = 400*2/3,                       
  units = "mm",
  dpi = 320
)

```

```{r for Bayesian models setting and sampling}

model_a <- brms::brm(
  a_value ~ 1 + a_condition,
  data = data_posterior_a_long,
  family = gaussian(),
  iter = 2000,
  warmup = 1000,
  chains = 4,
  cores = 4,
  seed = 42)

saveRDS(model_a, "../results/hddm/statistic_inference/model_a.rds")

model_v <- brms::brm(
  v_value ~ 1 + v_condition,
  data = data_posterior_v_long,
  family = gaussian(),
  iter = 2000,
  warmup = 1000,
  chains = 4,
  cores = 4,
  seed = 42)

saveRDS(model_v, "../results/hddm/statistic_inference/model_v.rds")

model_t <- brms::brm(
  t_value ~ 1 + t_condition,
  data = data_posterior_t_long,
  family = gaussian(),
  iter = 2000,
  warmup = 1000,
  chains = 4,
  cores = 4,
  seed = 42)

saveRDS(model_t, "../results/hddm/statistic_inference/model_t.rds")

```

```{r for statictic inference_Bayesian comparision}

model_names <- c("model_a", "model_v", "model_t")
model_paths <- paste0("../results/hddm/statistic_inference/", model_names, ".rds")

model_list <- lapply(model_paths, readRDS)

for (i in seq_along(model_names)) {
  model_name <- model_names[i]
  model <- model_list[[i]]
  
  trace_par_cue2vs1 <- as.data.frame(model)[,2]
  trace_par_cue3vs1 <- as.data.frame(model)[,3]
  trace_par_cue4vs1 <- as.data.frame(model)[,4]
  
  trace_par_cue3vs2 <- trace_par_cue3vs1-trace_par_cue2vs1
  trace_par_cue4vs2 <- trace_par_cue4vs1-trace_par_cue2vs1
  trace_par_cue4vs3 <- trace_par_cue4vs1-trace_par_cue3vs1
  
  hdi_3vs2 <- bayestestR::hdi(trace_par_cue3vs2, ci = 0.95)
  rope_res_2 <- bayestestR::rope(trace_par_cue3vs2, range = c(-0.001,0.001))
                                 
  hdi_4vs2 <- bayestestR::hdi(trace_par_cue4vs2, ci = 0.95)
  rope_res_3 <- bayestestR::rope(trace_par_cue4vs2, range = c(-0.001,0.001))
  
  hdi_4vs3 <- bayestestR::hdi(trace_par_cue4vs3, ci = 0.95)
  rope_res_4 <- bayestestR::rope(trace_par_cue4vs3, range = c(-0.001,0.001))
  
  p_3vs2 <- plot(rope_res_2, rope_color = "grey70") +
    papaja::theme_apa() +
    ggtitle(paste(model_name, 'cue3vs2'))
  
  p_4vs2 <- plot(rope_res_3, rope_color = "grey70") +
    papaja::theme_apa() +
    ggtitle(paste(model_name, 'cue4vs2'))
  
  p_4vs3 <- plot(rope_res_4, rope_color = "grey70") +
    papaja::theme_apa() +
    ggtitle(paste(model_name, 'cue4vs3'))
 
  final_plot <- patchwork::wrap_plots(p_3vs2, p_4vs2, p_4vs3, ncol = 3)
  
  final_plot_a <- patchwork::wrap_plots(plot_list_a, ncol = )
  final_plot_a+ggview::canvas(width = 400,height = 100*2/3, units = "mm", dpi = 320)
  ggplot2::ggsave(
    filename = paste0("../figure/final_plot_", sub("model_", "", model_name), ".jpg"),
    plot = final_plot,
    width = 400,
    height = 100 * 2 / 3,
    units = "mm",
    dpi = 320
  )
}
```